Add KeySets Support to Operator
IABTechLab/uid2-operator pull request #148
Opened 2023-07-11 03:30 UTC by zaiweidu

2023-07-12 18:51 UTC, cody-constine-ttd commented on scripts/aws/README.md
> +  "keyset_keys_metadata_path": "https://core-integ.uidapi.com/keyset_keys/refresh",
the path is keyset-keys

2023-07-12 18:51 UTC, cody-constine-ttd commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +                } else if (!keysets.canClientAccessKey(clientKey, key)) {
We might still need the mode here, because ID_READERs can get null keysets

2023-07-12 18:51 UTC, cody-constine-ttd commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
>                      keySet.put("keyset_id", DEFAULT_KEYSET_ID);
This should be the clients default Keyset ID now

2023-07-14 03:40 UTC, jon8787 commented
There are a few EncryptionKey references in EncryptionTest. Can we replace these with KeysetKey?

2023-07-14 03:53 UTC, jon8787 commented on conf/docker-config.json
> +  "keyset_metadata_path": "/com.uid2.core/test/keyset/metadata.json",
why do we not remove "keys_metadata_path" and "keys_acl_metadata_path" from all these json files?

2023-07-14 03:57 UTC, jon8787 commented on scripts/aws/make_config.py
> +  apply_override(config, integ_config, 'keyset_metadata_path', str)
should we remove the 2 "keys" lines above?

2023-07-14 06:16 UTC, jon8787 commented on src/main/java/com/uid2/operator/monitoring/OperatorMetrics.java
> +                                final KeysetKey key = EncryptionKeyUtil.getDefaultKeysetActiveKey(keysetKeyStore.getSnapshot(), keysetProvider, siteId, now);
do we also need to deal with non-default active keys?

2023-07-14 06:37 UTC, jon8787 commented on src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
> +                this.keysetKeyStore.getSnapshot(), this.keysetProvider, Const.Data.MasterKeySiteId, Const.Data.MasterKeySiteId, asOf);
I think we should have a different function where there is no fallback site id, because that's needed both here and for the refresh key

2023-07-14 06:54 UTC, jon8787 commented on src/main/java/com/uid2/operator/service/EncryptionKeyUtil.java
> +                .filter(d -> d.isDefault() == true)
can remove "== true"?

2023-07-14 06:56 UTC, jon8787 commented on src/main/java/com/uid2/operator/service/EncryptionKeyUtil.java
> +        Keyset defaultKeyset = !keysets.isEmpty() ? keysets.get(0) : null;
what happens if keysets > 1 ?

2023-07-14 06:56 UTC, jon8787 commented on src/main/java/com/uid2/operator/service/EncryptionKeyUtil.java
> +            return null;
should we log an error here?

2023-07-14 07:11 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +            int defaultKeysetId = DEFAULT_KEYSET_ID;
I think the above lines are not correct. We shouldn't be using these consts anymore, and should delete them from the repo

2023-07-14 07:17 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +                    if (keyset.isDefault()) defaultMasterKeysetId = key.getKeysetId();
Do we have non-default master keysets?

2023-07-14 10:23 UTC, jon8787 commented on src/main/resources/com.uid2.core/test/keyset/keyset.json
> +  {
can we remove keys.json and keys_acl.json?

2023-07-14 10:26 UTC, jon8787 commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +        //when(keysetProvider.getSnapshot()).thenReturn(keysetProviderSnapshot);
could remove this

2023-07-20 00:15 UTC, zaiweidu commented on scripts/aws/make_config.py
> +  apply_override(config, integ_config, 'keyset_metadata_path', str)
test

2023-07-20 13:26 UTC, zaiweidu commented on scripts/aws/README.md
> +  "keyset_keys_metadata_path": "https://core-integ.uidapi.com/keyset_keys/refresh",
Fixed the path.

2023-07-20 13:27 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
>                  keySet.put("id", key.getId());
Set the actual KeysetId.

2023-07-20 13:28 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
>                      keySet.put("keyset_id", DEFAULT_KEYSET_ID);
Replaced with keysetId of default keyset.

2023-07-20 13:29 UTC, zaiweidu commented on conf/docker-config.json
> +  "keyset_metadata_path": "/com.uid2.core/test/keyset/metadata.json",
Removed used "keys_metadata_path" and "keys_acl_metadata_path" keys.

2023-07-20 13:32 UTC, zaiweidu commented on src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
> +                this.keysetKeyStore.getSnapshot(), this.keysetProvider, Const.Data.MasterKeySiteId, Const.Data.MasterKeySiteId, asOf);
Added a wrapper function that only takes 1 siteId (no fallback).

2023-07-20 13:34 UTC, zaiweidu commented on src/main/java/com/uid2/operator/service/EncryptionKeyUtil.java
> +            return null;
Updated in the latest commit.

2023-07-20 13:35 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +            int defaultKeysetId = DEFAULT_KEYSET_ID;
Replaced with masterKeysetId and defaultKeysetId.

2023-07-20 13:36 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +                    if (keyset.isDefault()) defaultMasterKeysetId = key.getKeysetId();
Removed the .isDefault() check.

2023-07-20 13:39 UTC, zaiweidu commented on src/main/resources/com.uid2.core/test/keyset/keyset.json
> +  {
Removed keys.json and keys_acl.json.

2023-07-20 13:40 UTC, zaiweidu commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +        //when(keysetProvider.getSnapshot()).thenReturn(keysetProviderSnapshot);
Removed.

2023-07-20 13:50 UTC, zaiweidu commented on src/main/java/com/uid2/operator/service/EncryptionKeyUtil.java
> +        Keyset defaultKeyset = !keysets.isEmpty() ? keysets.get(0) : null;
One site can only have 1 default Keyset.

2023-07-21 03:42 UTC, jon8787 commented on src/main/java/com/uid2/operator/service/EncryptionKeyUtil.java
> +            return null;
If people call this method directly and there's no key, it will return null, but if they call the fallback method it will throw. Is this desired?

2023-07-21 03:44 UTC, jon8787 commented on src/main/java/com/uid2/operator/service/EncryptionKeyUtil.java
> +        Keyset defaultKeyset = !keysets.isEmpty() ? keysets.get(0) : null;
That's an assumption. If the assumption is found to be false, should we log an error?

2023-07-21 08:45 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +            int defaultKeysetId = EncryptionKeyUtil.getActiveKeyBySiteIdWithFallback(this.keysetKeyStore.getSnapshot(), keysetSnapshot, clientKey.getSiteId(), Const.Data.AdvertisingTokenSiteId, Insta
for sharing, we'd never want to fallback, so this should be getActiveKeyBySiteId()

2023-07-21 09:12 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +                Keyset keyset = this.keysetProvider.getSnapshot().getKeyset(key.getKeysetId());
1. We've already retrieved keysetSnapshot, why are we getting it again here?
2. Probably not correct to call getSnapshot() here because we could get a different snapshot in any iteration of the loop. So when we move to KeyManager, will need to solve that (either expose getSnapshot() after all, or extract this data from KeyManager with a new method)

2023-07-21 17:57 UTC, cody-constine-ttd reviewed
Can't currently run because the shared version is uncorrect in the pom.xml

2023-07-21 17:57 UTC, cody-constine-ttd commented on src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
> +            throw new RuntimeException(String.format("Cannot get active master key with SITE ID %d.", Const.Data.MasterKeySiteId));
We should probably log an error here

2023-07-21 17:57 UTC, cody-constine-ttd commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +            int defaultKeysetId = EncryptionKeyUtil.getActiveKeyBySiteIdWithFallback(this.keysetKeyStore.getSnapshot(), keysetSnapshot, clientKey.getSiteId(), Const.Data.AdvertisingTokenSiteId, Insta
Can't we set defaultKeysetId as we look through the keys anyways? We are doing an extra loop through all the keys here

2023-07-21 17:57 UTC, cody-constine-ttd commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +        /* Reviewers to confirm: whether we need to check MissingAclMode by client's role.
I don't think a toJson method should have logic about who can access keys TBH, but if we want to keep this the way it is, then it probably needs the mode

2023-07-21 17:57 UTC, cody-constine-ttd commented on src/test/java/com/uid2/operator/RotatingKeysetKeyStoreTest.java
> +package com.uid2.operator;
Why are we testing RotatingKeysetKeyStore here? There is already test for it in Shared

2023-07-21 17:57 UTC, cody-constine-ttd commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +    private void linkKeysToKeysets(KeysetKey[] keys, Keyset[] keysets) {
I know you explained this function to me, but I still don't understand its purpose. Keys and Keysets should be linked by keyset ID

2023-07-24 01:20 UTC, jon8787 commented on conf/default-config.json
> +  "master_key_keyset_id": 1,
Why do we put these ids in config rather than a const? To me, the main reason to do this would be if we wanted different values between environments. But I think that's something we don't want here.

Site ids don't work like this, eg Data.MasterKeySiteId does not come from a config

2023-07-24 02:40 UTC, jon8787 commented on src/main/java/com/uid2/operator/model/KeyManager.java
> +            return null;
Concerns me that we don't log or throw here. I think there's a bug in one of the calling methods, because it doesn't throw or check for null.
Can we add getMasterKey and getRefreshKey methods in KeyManager which throw on failure?

2023-07-24 03:01 UTC, jon8787 commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +        when(keysetKeyStoreSnapshot.getActiveKey(eq(3), any())).thenReturn(siteKey);
the above is another reason we should use consts for refresh keyset id etc - the above looks like it depends on a specific config being used

2023-07-24 05:26 UTC, jon8787 commented on src/main/java/com/uid2/operator/model/KeyManager.java
> +    public KeysetKey getActiveKey(int keysetId, Instant now) {
can this be private?

2023-07-24 06:37 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +                .stream().filter(k -> keysetMap.containsKey(k.getKeysetId()) && keysetMap.get(k.getKeysetId()).getSiteId() != Data.RefreshKeySiteId)
We shouldn't need to use RefreshKeySiteId since we know RefreshKey's keyset id

2023-07-24 14:08 UTC, jon8787 commented on src/main/java/com/uid2/operator/Const.java
> +    public static Object Data;
what's this for?

2023-07-24 14:09 UTC, jon8787 commented on src/main/java/com/uid2/operator/Main.java
> +            UIDOperatorVerticle verticle = new UIDOperatorVerticle(config, clientKeyProvider, keysetKeyStore, keysetProvider, saltProvider, optOutStore, Clock.systemUTC(), _statsCollectorQueue);
can we pass keyManager here instead?

2023-07-24 14:12 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/ClientVersionCapturingHandler.java
> +import com.uid2.operator.Const;
why do we need this change?

2023-07-24 14:35 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +            // include 'keyset_id' field, if:
we don't want fallback here

2023-07-24 14:43 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +        /* Reviewers to confirm: whether we need to check MissingAclMode by client's role.
Can we write a test case that will discover if anything's wrong here?

2023-07-24 15:07 UTC, jon8787 commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
>      }
Do we really need all these mocks? Can we just mock RotatingKeysetProvider.getSnapshot() and IKeysetKeyStore.getSnapshot() instead?

2023-07-24 17:16 UTC, cody-constine-ttd commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +    void setKeysets(Map<Integer, Keyset> keysets) {
Why did you go back on the way I setup the keysets and keysetKeys?

2023-07-24 17:39 UTC, zaiweidu commented on conf/default-config.json
> +  "master_key_keyset_id": 1,
converted to Const.

2023-07-24 19:55 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +    private List<KeysetKey> getKeysetKeys() {
Fixed.

2023-07-24 19:57 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +                } else if (keyset.getSiteId() == Data.MasterKeySiteId && keyset.isEnabled()) {
keys from client's disabled keysets won't return to client.

2023-07-24 19:59 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +            // include 'keyset_id' field, if:
Removed fallback.

2023-07-24 22:31 UTC, zaiweidu commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
>      }
This's one of many historical tests that need a cleanup later. I'll create a Continous Improvement ticket to track the work.

2023-07-24 22:35 UTC, zaiweidu commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +    void setKeysets(Map<Integer, Keyset> keysets) {
It was conflicting with my other Mockito interceptions. I've refactored it to an embedded class to work for my DSP & Pub tests. We do need Continous Improvement ticket to clean up / refactor unit tests on Operator.

2023-07-24 23:42 UTC, CodyConstine commented on src/main/java/com/uid2/operator/Const.java
> +        public static final int MasterKeyKeysetId = 1;
We made these const in shared

2023-07-25 00:01 UTC, zaiweidu commented on src/main/java/com/uid2/operator/Const.java
> +        public static final int MasterKeyKeysetId = 1;
I was thinking the same thing. But I can't wait for the tiny thing. I'll include it in Continuous Improvement ticket.

2023-07-25 00:26 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +        /* Reviewers to confirm: whether we need to check MissingAclMode by client's role.
ID_READER & GENERATOR test cases are added.

2023-07-25 00:26 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +            int defaultKeysetId = EncryptionKeyUtil.getActiveKeyBySiteIdWithFallback(this.keysetKeyStore.getSnapshot(), keysetSnapshot, clientKey.getSiteId(), Const.Data.AdvertisingTokenSiteId, Insta
Logger added.

2023-07-25 00:39 UTC, zaiweidu commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +    private void linkKeysToKeysets(KeysetKey[] keys, Keyset[] keysets) {
If we want to use the real logic of key lookup and sharing defined in Shared instead of mocks, we have to instantiate StoreSnapshot and ProviderSnapshot and make them cross referrenced by Keyset ID. This is exactly what I'm doing in _linkKeysToKeysets()_.

2023-07-25 01:19 UTC, jon8787 commented on src/main/java/com/uid2/operator/Const.java
> +        public static final int MasterKeyKeysetId = 1;
@zaiweidu please see https://github.com/IABTechLab/uid2-shared/commit/691c76475f246a9587cccdcd4f1f96814a19cab3 , no need to wait

2023-07-25 01:32 UTC, jon8787 commented on src/main/java/com/uid2/operator/Main.java
> +        this.keyManager = new KeyManager(this.keysetKeyStore, this.keysetProvider);
Doesn't seem right that we store keyManager as a member but then re-create it on line 217. How about we remove the member variable and replace with a getKeyManager() function?

2023-07-25 02:36 UTC, zaiweidu commented on src/main/java/com/uid2/operator/Const.java
> +        public static final int MasterKeyKeysetId = 1;
picked it up.

2023-07-25 02:38 UTC, jon8787 commented on src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
> +                    new OperatorIdentity(0, OperatorType.Service, 0, masterKeyId),
why do we need these changes?

2023-07-25 02:47 UTC, zaiweidu commented on src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
> +                    new OperatorIdentity(0, OperatorType.Service, 0, masterKeyId),
@cody-constine-ttd made the specific change.

2023-07-25 04:36 UTC, jon8787 commented on src/main/java/com/uid2/operator/Const.java
> +        public static final int MasterKeyKeysetId = 1;
I don't see it.

2023-07-25 05:00 UTC, jon8787 commented on src/main/java/com/uid2/operator/service/RoutingContextReader.java
> +import com.uid2.operator.Const;
can we revert this?

2023-07-25 05:19 UTC, jon8787 commented on src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
> +                    new OperatorIdentity(0, OperatorType.Service, 0, masterKeyId),
let's find out

2023-07-25 05:30 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +                } else if (keyset.getSiteId() == Data.MasterKeySiteId && keyset.isEnabled()) {
how? this "if" statement is only about keyset_id, not about other fields in the key

2023-07-25 05:31 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +                } else if (!this.keyManager.canClientAccessKey(clientKey, key, mode)) {
what will happen if getSnapshot() returns a new snapshot inside this loop?

2023-07-25 05:33 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +            if (!this.keyManager.canClientAccessKey(clientKey, k, mode)) {
what happens if the getSnapshot() call returns a new snapshot inside this loop?

2023-07-25 05:34 UTC, jon8787 commented on src/test/java/com/uid2/operator/TokenEncodingTest.java
should we be using KeyManager as a member instead of these 2?

2023-07-25 05:41 UTC, jon8787 commented on src/main/java/com/uid2/operator/model/KeyManager.java
> +    public KeysetKey getActiveKey(int keysetId, Instant now) {
I don't see it. Which unit test depends on this method being public?

2023-07-25 05:55 UTC, jon8787 commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +     * SHARING TESTS
These are DSP tests too?

2023-07-25 06:06 UTC, jon8787 commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +
- Instead of test1, test2, can we name these to be human readable? eg "SameSiteId", "MissingAllowedSites", "AllowedSitesIncludeUs"
- Even better if we could make these separate tests and use common functions to do the setup and asserts

2023-07-25 09:06 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +                } else if (!this.keyManager.canClientAccessKey(clientKey, key, mode)) {
Take a snapshot on keysets out side of loop.

2023-07-25 09:08 UTC, zaiweidu commented on src/main/java/com/uid2/operator/Main.java
> +        this.keyManager = new KeyManager(this.keysetKeyStore, this.keysetProvider);
Replaced member this.keyManager with getKeyManager() method.

2023-07-25 09:15 UTC, zaiweidu commented on src/test/java/com/uid2/operator/TokenEncodingTest.java
Fixed as recommended.

2023-07-25 09:16 UTC, zaiweidu commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +     * SHARING TESTS
DSPs & Pubs are down below.

2023-07-25 09:36 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +            if (!this.keyManager.canClientAccessKey(clientKey, k, mode)) {
Cached snapshot and keysets outside of loop.

2023-07-25 09:44 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +                Keyset keyset = this.keysetProvider.getSnapshot().getKeyset(key.getKeysetId());
Cached a keysetSnapshot outside of loop and use inside.

2023-07-25 09:46 UTC, zaiweidu commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +        when(keysetKeyStoreSnapshot.getActiveKey(eq(3), any())).thenReturn(siteKey);
Applied hardcoded keyset IDs for master/refresh/publisher. The values are defined in Shared.

2023-07-25 09:55 UTC, zaiweidu commented on src/main/java/com/uid2/operator/model/KeyManager.java
> +    public KeysetKey getActiveKey(int keysetId, Instant now) {
Refactor code and make it private.

2023-07-25 10:16 UTC, zaiweidu commented on src/main/java/com/uid2/operator/model/KeyManager.java
> +            return null;
Logs added before throw.

2023-07-25 12:08 UTC, jon8787 commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +
I still see "test1", "test2", "test3", "test4"

2023-07-25 20:27 UTC, zaiweidu commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +
I didn't push... avoid disturbing your review. I renamed the test cases with meaningful names in the latest push.

2023-07-25 20:31 UTC, zaiweidu commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +                } else if (!this.keyManager.canClientAccessKey(clientKey, key, mode)) {
I have refactored KeyManager class to support Snapshot mode. KeyManager::Snapshot() will cache keys/keysets within its lifetime. This solves the consistency concern here and the other location.

2023-07-25 20:35 UTC, zaiweidu commented on src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
> +                    new OperatorIdentity(0, OperatorType.Service, 0, masterKeyId),
This change was made to test & validate 'token/generate' in the new test case tokenGenerateRotatingKeysets_GENERATOR()

2023-07-26 03:20 UTC, jon8787 commented on src/main/java/com/uid2/operator/service/EncryptedTokenEncoder.java
> +                    new OperatorIdentity(0, OperatorType.Service, 0, masterKeyId),
Ok got it. decodeAdvertisingToken() is only used by /token/validate and tests. /token/validate doesn't use these values, and tests never consumed these values until now.

2023-07-27 02:41 UTC, zaiweidu reviewed
Please review.

2023-07-27 04:34 UTC, jon8787 commented on src/test/java/com/uid2/operator/RotatingKeysetKeyStoreTest.java
> +package com.uid2.operator;
Could you explain a bit further? Why are we testing it here and not in shared?

2023-07-27 16:35 UTC, zaiweidu commented on src/main/java/com/uid2/operator/model/KeyManager.java
> +            return null;
I've removed the log as we throw the error.

2023-07-27 16:56 UTC, zaiweidu reviewed
@jon8787 Please review.

2023-07-27 16:56 UTC, zaiweidu commented on src/test/java/com/uid2/operator/RotatingKeysetKeyStoreTest.java
> +package com.uid2.operator;
These tests don't test functionality of rotating key store or provider, but The ensure existence of test json (filenames & paths) for Operator unit tests. This can't be done in Shared.

2023-07-31 03:07 UTC, zaiweidu commented on src/main/java/com/uid2/operator/monitoring/OperatorMetrics.java
> +                                final KeysetKey key = EncryptionKeyUtil.getDefaultKeysetActiveKey(keysetKeyStore.getSnapshot(), keysetProvider, siteId, now);
Per our discussion today, let's only monitor active keys from default keysets for now. I've create UID2-1556 as Continuous Improvement to track the future work.

2023-07-31 03:08 UTC, zaiweidu reviewed
will do more local integration tests.

2023-08-08 07:32 UTC, jon8787 requested changes

2023-08-09 06:26 UTC, closed without merging