Respond with 400 instead of 500 when CSTG request validation fails
IABTechLab/uid2-operator pull request #633
Opened 2024-06-16 06:39 UTC by caroline-ttd

2024-06-17 00:38 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +        if (this.phoneSupport ? !checkTokenInputV1(input, rc) : !checkTokenInput(input, rc)) {
This expression `this.phoneSupport ? !checkTokenInputV1(input, rc) : !checkTokenInput(input, rc)` appears 6 times in this file and ideally should be wrapped in a method

2024-06-17 00:38 UTC, jon8787 commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +    void cstgInvalidPhoneHashInput(Vertx vertx, VertxTestContext testContext) throws NoSuchAlgorithmException, InvalidKeyException {
possible to eliminate some of the duplication? the tests are identical other than the input. Can the input be parameterized?

2024-06-17 05:19 UTC, mcollins-ttd commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +        if (this.phoneSupport ? !checkTokenInputV1(input, rc) : !checkTokenInput(input, rc)) {
The only difference between `checkTokenInputV1` and `checkTokenInput` is the error message returned.

Can we remove `checkTokenInputV1` and do the `this.phoneSupport` check in `checkTokenInput`?

2024-06-17 22:34 UTC, caroline-ttd commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +        if (this.phoneSupport ? !checkTokenInputV1(input, rc) : !checkTokenInput(input, rc)) {
I removed the `checkTokenInputV1` and did the `this.phoneSuppor`t check in `checkTokenInput`. Also invert the method.

2024-06-17 22:35 UTC, caroline-ttd commented on src/test/java/com/uid2/operator/UIDOperatorVerticleTest.java
> +    void cstgInvalidPhoneHashInput(Vertx vertx, VertxTestContext testContext) throws NoSuchAlgorithmException, InvalidKeyException {
That is a good idea, I used the `@ParameterizedTest`

2024-06-18 02:06 UTC, jon8787 requested changes

2024-06-18 02:06 UTC, jon8787 commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +        if (checkTokenInput(input, rc)) {
`if (checkTokenInput)` makes it seem like it succeeded. How about we rename this method to `checkForInvalidTokenInput`?

2024-06-18 21:29 UTC, caroline-ttd commented on src/main/java/com/uid2/operator/vertx/UIDOperatorVerticle.java
> +        if (checkTokenInput(input, rc)) {
I rename checkTokenInput to checkForInvalidTokenInput. true for invalid input, false for valid input.

2024-06-18 23:38 UTC, jon8787 approved these changes

2024-06-20 18:55 UTC, merged